spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost/iterators?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: IteratorsHikariCP
      minimum-idle: 5
      idle-timeout: 18000
      connection-timeout: 3000
      max-lifetime: 1800000
    initialization-mode: always # 执行schema的初始化
    schema: classpath:schema.sql
    data: classpath:data.sql
