spring:
  profiles:
    active: dev
---
spring:
  main:
    banner-mode: off
  config:
    activate:
      on-profile: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:db_users;MODE=MYSQL;
    username: root
    password: root
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: IteratorsHikariCP
      minimum-idle: 5
      idle-timeout: 18000
      connection-timeout: 3000
      max-lifetime: 1800000
    initialization-mode: always # 执行schema的初始化
    schema: classpath:schema.sql
    data: classpath:data.sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml